<?php include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title"><?php echo $data['pageTitle'];?></h1>
            </div>
            <div class="col-sm-3 position-relative hide-for-small">
                <img class="sidebar-image growing-sidebar-left-image" src="<?php echo $data['imagesDirectory'].'growing-up/sleep.jpg';?>"/>
            </div>
            <div class="col-sm-12 col-md-6">
                <p>
                    By the time Zero was 9 months old, he had stopped physically growing but his personality continued to develop.  For instance, he carried on a battle of wits with his owner regarding being alone; his owner would give him a big treat and leave for work and Zero would bring him back by crying until his owner's landlord called him.
                </p>
                <p>
                    And because he was larger he could do more stuff.  For example, he got to go to the annual Pride Parade in <a href="/favourites/places" class="text-decoration">Toronto</a> and was adored by many as his rode upon his owner's shoulders.
                </p>
                <p>
                    Thankfully, Zero's teething and neutering came and went fairly smoothly during this phase.  The only hiccup was Zero's veterinarian taking a weekend off and so Zero could not get his stitches out for an extra 3 days!
                </p>
            </div>
            <div class="col-sm-3 position-relative hide-for-small">
                <img class="sidebar-image growing-sidebar-right-image" src="<?php echo $data['imagesDirectory'].'growing-up/coat.jpg';?>"/>
            </div>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');