<?php include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title"><?php echo $data['pageTitle'];?></h1>
            </div>
            <div class="col-sm-3 position-relative hide-for-small">
                <img class="sidebar-image growing-sidebar-left-image" src="<?php echo $data['imagesDirectory'].'growing-up/chair.jpg';?>"/>
            </div>
            <div class="col-sm-12 col-md-6">
                <p>
                    While Zero does not always act like an adult (he still has plenty of energy and can get into plenty of mischief), he is approaching his third birthday in January.  For his birthday he normally gets a rawhide bone and a new toy so he likes to join in the celebration.
                </p>
                <p>
                    Zero's move to Ireland was not a concern although he still worries from time to time about the mailman coming up to the front door.  He is making new friends in Ireland, like Pepper the white Jack Russel Terrier, and Zero is enjoying the moderate weather compared to Toronto.
                </p>
                <p>
                    As Zero gets older, he goes to bed earlier than he used to (he used to be quite a night owl) and he eats less overall but he still enjoys his treats and his <a href="/favourites" class="text-decoration">favourites</a>.
                </p>
            </div>
            <div class="col-sm-3 position-relative hide-for-small">
                <img class="sidebar-image growing-sidebar-right-image" src="<?php echo $data['imagesDirectory'].'growing-up/pepper.jpg';?>"/>
            </div>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');