<?php include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title"><?php echo $data['pageTitle'];?></h1>
            </div>
            <div class="col-sm-3 position-relative hide-for-small">
                <img class="sidebar-image growing-sidebar-left-image" src="<?php echo $data['imagesDirectory'].'growing-up/chewing.jpg';?>"/>
            </div>
            <div class="col-sm-12 col-md-6">
                <p>
                    Zero was a very, very small puppy; he was smaller than a shoe at 8 weeks old.  Even though puppy kibble was purchased for him, it still had to be broken into pieces so that he could chew it.
                </p>
                <div class="youtube">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/4BC4N4tOQIg" frameborder="0" allowfullscreen></iframe>
                </div>
                <p>
                    As he grew, Zero quickly developed his jaw strength by chewing on everything. (He even chewed on the wire bars of his kennel from time to time!)  His favourite chew toys were a rubber circle and his Kong which was filled with peanut butter.
                </p>
                <p>
                    When Zero was young, his owner gave him the cardboard tubes inside of paper towel rolls to place with.  While this supplied him with a large amount of entertainment, Zero apparantely did not distinguish between different kinds of paper and so he ripped up much of his owner's sheet music one day.
                </p>
            </div>
            <div class="col-sm-3 position-relative hide-for-small">
                <img class="sidebar-image growing-sidebar-right-image" src="<?php echo $data['imagesDirectory'].'growing-up/boot.jpg';?>"/>
            </div>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');