<?php include_once($data['viewsDirectory'].'helpers/helpers.php');
include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main class="container">
        <div class="row">
            <?php include_once('partials/sidebar.phtml');?>
            <div class="col-sm-12 col-md-8">
                <p>
                    Zero and Basil have known each other since they were puppies.  They met when Basil and his owner were walking down the street on their way to the dog park.  Basil is a couple months older than Zero and Zero could not go to the dog park yet so Basil and Zero played on the front lawn instead.  Basil was so tired after playing that they did not need to go to the park after all!
                </p>
                <p>
                    Basil and Zero continued to see each other in the neighborhood and at the dog park (once Zero was older that is).  Basil's owner even watched Zero a couple times so that they could play while Zero's owner was at work.  This video shows them playing when they were around 1 year old.
                </p>
                <div class="youtube">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/C-5MsOgKYW0" frameborder="0" allowfullscreen></iframe>
                </div>
                <p>
                    Zero had to leave Basil in Toronto when he moved to Ireland but he's sure to see him again when Zero comes back to visit!
                </p>
            </div>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');