<?php include_once($data['viewsDirectory'].'helpers/helpers.php');
include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main class="container">
        <div class="row">
            <?php include_once('partials/sidebar.phtml');?>
            <div class="col-sm-12 col-md-8">
                <p>
                    Kaycee is Zero's (younger) aunt; her owners are the parents of Zero's owner.  Zero and Kaycee first met when Kaycee was only 3 months old.  They were playing fetch in the backyard but Zero was faster and kept getting the ball first so two balls were thrown instead so that Kaycee could get one too.  Zero got his ball and stood by it and Kaycee chased hers but as soon as she realized that Zero was not running with her, she turned and ran towards him however she could not stop in time and ran him over.  Zero was not happy and I'm pretty sure he still holds a grudge to this day.
                </p>
                <img class="body-image" src="<?php echo $data['imagesDirectory'];?>barkbook/zero-kaycee.jpg" alt="Zero and Kaycee"/>
                <p>
                    Since then Zero and Kaycee have become better friends, partially due to Kaycee losing some of her puppy energy and partially due to them having separate toys to play with.  Kaycee has gotten quite big, as can be seen in the video about <a class="text-decoration" href="/favourites/toys">Zero's toys</a>, and she uses her size advantage to take Zero's things and pull his tail when chasing him.  In return Zero makes sure to run through small spaces and take tight corners to get Kaycee stuck and he will take his bones back from her (once she's not looking of course).
                </p>
            </div>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');