<?php include_once($data['viewsDirectory'].'helpers/helpers.php');
include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main class="container">
        <div class="row">
            <?php include_once('partials/sidebar.phtml');?>
            <div class="col-sm-12 col-md-8">
                <p>
                    Quinn was only 3 months old when he first met Zero.  Quinn decided to come to Zero's owner's office for a board game night (and to celebrate Friday).  Zero did not like Quinn at first because Quinn just wanted to lick Zero's face.  But once Zero and Quinn swapped toys they were as thick as thieves.  Quinn did not really know what was going on but once Zero wanted a toy, Quinn dropped it and once Quinn dropped a toy, Zero took it.
                </p>
                <p>
                    Quinn and Zero's friendship was just beginning when Zero moved to Ireland but Zero is already making plans to come back and visit his friends in Toronto.
                </p>
            </div>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');