<?php include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title"><?php echo $data['pageTitle'];?></h1>
            </div>
            <div class="col-sm-3 position-relative hide-for-small">
                <img class="sidebar-image favourites-sidebar-left-image" src="<?php echo $data['imagesDirectory'].'favourites/lake.jpg';?>"/>
            </div>
            <div class="col-sm-12 col-md-6">
                <h3>Toronto</h3>
                <p>
                    Zero was born a few hours drive north of Toronto in a little farming town but Toronto was where he grew up.  Zero lived in two areas of the city, the Annex near the city centre and Roncesvalles Village on the west end.  Zero had a lot more dog friends in the Annex but he liked the dog parks better in Roncesvalles.
                </p>
                <h3>Wisconsin</h3>
                <p>
                    He was not able to go until he was a year and a half but Zero had a great time when he was able to go to the lake in Wisconsin.  He enjoyed jumping off of the dock in the water and rolling around in the grass to get dry.
                </p>
                <h3>North Carolina</h3>
                <p>
                    Just before moving to Dublin, Zero got to visit the farm in North Carolina.  It was his first experience meeting cows and while he did not think the baby cow was very threatening, he ran away very quickly when the calf's mother came over.
                </p>
                <h3>Dublin</h3>
                <p>
                    Zero loves Dublin, specifically the picture window to look through during the day and sun himself in.  He always enjoys Waterville park and going to the pet store in Blanchardstown Shopping Centre.
                </p>
            </div>
            <div class="col-sm-3 position-relative hide-for-small">
                <img class="sidebar-image favourites-sidebar-right-image" src="<?php echo $data['imagesDirectory'].'favourites/farm.jpg';?>"/>
            </div>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');