<?php include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title"><?php echo $data['pageTitle'];?></h1>
            </div>
            <div class="col-sm-3 position-relative hide-for-small">
                <img class="sidebar-image favourites-sidebar-left-image" src="<?php echo $data['imagesDirectory'].'favourites/penguin.jpg';?>"/>
            </div>
            <div class="col-sm-12 col-md-6">
                <h3>#1 - Penguin</h3>
                <p>
                    Zero &ldquo;earned&rdquo; his penguin after successfully waking up visiting company at 6am by squeaking his other toys non-stop.  His penguin has a silent squeaker which only sounds at frequencies above the normal human hearing range.  Since the first day he got it, Zero has preferred his penguin over all of his other toys and often sleeps with his head on it like a pillow.
                </p>
                <h3>#2 - Pig</h3>
                <p>
                    Another soft toy, Zero's pig was the first toy he ever got.  When Zero's owner went to pick Zero out from the litter, the breeder put the pig in the pen and Zero was the only puppy who wanted to play with it.  Needless to say, they went home together and have accompanied each other ever since.
                </p>
                <h3>#3 - Tennis Ball</h3>
                <p>
                    Zero has had many different kinds of balls to play with, ranging from soccer balls to racquetballs to ping pong balls (when he can get them!), but as soon as his friend <a href="/barkbook/basil"  class="text-decoration">Basil</a> first showed up to the <a href="/favourites/places" class="text-decoration">park</a> with one, Zero became a tennis ball fanatic.  Over time Zero has cultivated his tennis ball preferences such that he really only goes crazy for the small tennis balls that have a squeaker in them.  He is so obsessed that his owner has to put it out of sight in order to get Zero to focus.
                </p>
            </div>
            <div class="col-sm-3 position-relative hide-for-small">
                <img class="sidebar-image favourites-sidebar-right-image" src="<?php echo $data['imagesDirectory'].'favourites/tennis-ball.jpg';?>"/>
            </div>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');