<?php include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h1>404 - Not Found</h1>
                <h3>Sorry, we could not find what you are looking for.</h3>  
            </div>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');