<?php
include_once($data['viewsDirectory'].'partials/header.phtml');
if(empty($exception)){ ?>
    <main class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h1>500 - Error</h1>
                <h3>Sorry, something went wrong.  Please try again later.</h3>
            </div>
        </div>
    </main>
<?php } else {
    var_dump($exception);
}
include_once($data['viewsDirectory'].'partials/footer.phtml');