<?php include_once($data['viewsDirectory'].'helpers/helpers.php');
include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title"><?php echo $data['pageTitle'];?></h1>
                <p>
                    Zero has met many dogs on the street, at dog parks, and with friends and family.  He keeps a Barkbook to keep in touch with his favourites.
                </p>
            </div>
            <?php foreach($barkbookData as $friend){ ?>
                <div class="col-sm-12 col-md-6 col-lg-3 barkbook-list-container">
                    <a href="/barkbook/<?php echo getVariable($friend,'url');?>">
                        <div class="barkbook-list-outer-border">
                            <div class="barkbook-list-inner-border">
                                <img class="barkbook-list-image" src="<?php echo $data['imagesDirectory'].'barkbook/'.getVariable($friend,'image');?>"/>
                                <h4 class="barkbook-list-title">
                                    <?php echo getVariable($friend,'name');?>
                                </h4>
                            </div>
                        </div>
                    </a>
                </div>
            <?php } ?>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');