<?php
$activitiesUrl = '/favourites/activities';
$placesUrl = '/favourites/places';
$toysUrl = '/favourites/toys';
include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main id="page-favourites" class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title"><?php echo $data['pageTitle'];?></h1>
            </div>
            <div class="col-sm-3 col-md-2 text-center position-relative">
                <i class="fa fa-gamepad" aria-hidden="true"></i>
            </div>
            <div class="col-sm-9 col-md-10">
                <h3 class="text-decoration">
                    <a href="<?php echo $activitiesUrl;?>">Activities</a>
                </h3>
                <p>
                    Zero has always been a very active dog.  Because of this, he needed a lot of training and entertainment to keep him busy.  These are some of his favourite things to do<a href="<?php echo $activitiesUrl;?>">...</a>
                </p>
            </div>
            <div class="col-sm-3 col-md-2 text-center position-relative">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
            </div>
            <div class="col-sm-9 col-md-10">
                <h3 class="text-decoration">
                    <a href="<?php echo $placesUrl;?>">Places</a>
                </h3>
                <p>
                    From the dog parks of Toronto to the cow pastures of the farm in North Carolina to the grassy fields of Dublin, Zero has several favourite places to visit<a href="<?php echo $placesUrl;?>">...</a>
                </p>
            </div>
            <div class="col-sm-3 col-md-2 text-center position-relative">
                <i class="fa fa-futbol-o" aria-hidden="true"></i>
            </div>
            <div class="col-sm-9 col-md-10">
                <h3 class="text-decoration">
                    <a href="<?php echo $toysUrl;?>">Toys</a>
                </h3>
                <p>
                    Toys are one of Zero's big passions and he has a lot of them!  However, his favourites are his most prized out of his collection<a href="<?php echo $toysUrl;?>">...</a>
                </p>
            </div>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');