<?php
$carouselImages = [
    'sleep.jpg',
    'coat.jpg',
    'couch.jpg',
    'woofstock.jpg'
];

include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main>
        <section class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h1 class="page-title"><?php echo $data['pageTitle'];?></h1>
                </div>
            </div>
        </section>
        <section>
            <div class="image-carousel">
                <?php foreach($carouselImages as $image){ ?>
                    <div>
                        <img src="<?php echo $data['imagesDirectory'].'gallery/'.$image;?>" />
                    </div>
                <?php } ?>
            </div>
        </section>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');