<?php
$puppyhoodUrl = '/growing-up/puppyhood';
$adolescenceUrl = '/growing-up/adolescence';
$adulthoodUrl = '/growing-up/adulthood';
include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main id="page-favourites" class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title"><?php echo $data['pageTitle'];?></h1>
            </div>
            <div class="col-sm-3 col-md-2 text-center position-relative">
                <i class="fa fa-hourglass-start" aria-hidden="true"></i>
            </div>
            <div class="col-sm-9 col-md-10">
                <h3 class="text-decoration">
                    <a href="<?php echo $puppyhoodUrl;?>">Puppyhood</a>
                </h3>
                <p>
                    Zero started out as a teeny, tiny puppy with a <em>BIG</em> personality.  He quickly grew from a pint-sized pup to a gangly youth<a href="<?php echo $puppyhoodUrl;?>">...</a>
                </p>
            </div>
            <div class="col-sm-3 col-md-2 text-center position-relative">
                <i class="fa fa-hourglass-half" aria-hidden="true"></i>
            </div>
            <div class="col-sm-9 col-md-10">
                <h3 class="text-decoration">
                    <a href="<?php echo $adolescenceUrl;?>">Adolescence</a>
                </h3>
                <p>
                    Zero's &ldquo;awkward&rdquo; months had a lot of difficult moments (teething, neutering) but he pulled through and had a lot of fun<a href="<?php echo $adolescenceUrl;?>">...</a>
                </p>
            </div>
            <div class="col-sm-3 col-md-2 text-center position-relative">
                <i class="fa fa-hourglass-end" aria-hidden="true"></i>
            </div>
            <div class="col-sm-9 col-md-10">
                <h3 class="text-decoration">
                    <a href="<?php echo $adulthoodUrl;?>">Adulthood</a>
                </h3>
                <p>
                    Zero has grown and rounded out over the years but he still knows how to have a good time<a href="<?php echo $adulthoodUrl;?>">...</a>
                </p>
            </div>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');