<div class="col-sm-12">
    <a class="link-barkbook-back" href="/barkbook"><i class="fa fa-chevron-left" aria-hidden="true"></i> Back to Barkbook</a>
</div>
<div id="barkbook-sidebar-container" class="col-sm-12 col-md-4">
    <img src="<?php echo $data['imagesDirectory'].'barkbook/'.getVariable($barkbookData,'image');?>" alt="<?php echo getVariable($barkbookData,'name');?>"/>
    <h1><?php echo getVariable($barkbookData,'name');?></h1>
    <p><strong>Age:</strong> <?php echo getVariable($barkbookData,'age');?></p>
    <p><strong>Breed:</strong> <?php echo getVariable($barkbookData,'breed');?></p>
    <p><strong>Location:</strong> <?php echo getVariable($barkbookData,'location');?></p>
    <p><strong>Friendship Level:</strong> <?php echo getVariable($barkbookData,'friendship');?></p>
</div>